services:
  - type: web
    name: code-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    healthCheckPath: "/"
    openPorts:
      - 8080
